#!/usr/bin/env bash

input=$1
date=${input/.*/}

lines=`wc -l $input | awk '{print $1}'`
smoothing="smooth acsplines"

# smooth acsplines neads at least four points
if [ $lines -ge 4 ]; then

    /usr/bin/gnuplot <<EOF

    set style data lines
    set timefmt "%H:%M:%S"
    set format x "%H:%M"
    set xdata time

    set terminal png
    set output "$date.png"

    plot "$input" using 1:2:(1.0) title "Northbound" \
              $smoothing, \
         "$input" using 1:3:(1.0) title "Southbound" \
              $smoothing

    set terminal svg
    set output "$date.svg"
    replot
EOF
fi

